stages:
    - static

default:
  tags:
    - podman

static-copy:
    stage: static
    image: harbor.wolke.img.univie.ac.at/podman/alpine-sshpass:latest
    when: manual
    script:
        - sshpass -p "$WOLKE_PASSWORD" rsync -autv --delete -e "ssh -o StrictHostKeyChecking=no" ./Documentation/html/* "$WOLKE_USER@wolke.img.univie.ac.at:/var/www/flexpart/flexextract"
